#Minecraft server properties
#Sat May 01 13:05:09 GMT 2021
spawn-protection=16
max-tick-time=60000
query.port=25565
server-name=Dedicated Server
generator-settings=
sync-chunk-writes=true
force-gamemode=false
allow-nether=true
enforce-whitelist=false
gamemode=survival
broadcast-console-to-ops=true
enable-query=true
text-filtering-config=
player-idle-timeout=0
difficulty=peaceful
broadcast-rcon-to-ops=true
spawn-monsters=true
op-permission-level=4
pvp=true
entity-broadcast-range-percentage=100
snooper-enabled=true
level-type=normal
enable-status=true
hardcore=false
enable-command-block=true
network-compression-threshold=256
max-players=20
max-world-size=29999984
resource-pack-sha1=
function-permission-level=2
rcon.port=25575
server-port=25565
debug=false
texture-pack=
server-ip=
spawn-npcs=true
allow-flight=false
level-name=world
view-distance=10
resource-pack=
spawn-animals=true
white-list=false
rcon.password=minecraft
generate-structures=true
online-mode=true
max-build-height=256
level-seed=
use-native-transport=true
prevent-proxy-connections=false
enable-jmx-monitoring=false
rate-limit=0
motd=Evans Family Minecraft Server
enable-rcon=true
